### ISSUE TITLE
bpnet fit failed with Mac M2

### ISSUE THREAD

**Issue by wangmhan** [jmschrei/bpnet-lite#23]
Thank you for the nice package!

I tried to follow the tutorial, however failed at the step of bpnet fit on both Mac and server.
It seems the issue is caused by: torch-not-compiled-with-cuda
The error message is: 
    AssertionError: Torch not compiled with CUDA enabled

I tried to modify the script by:
1) adding torch.set_default_device("mps")
2) replace cuda() to .to(device), device = torch.device("cpu")
None of them worked...

I noticed that in tangermeme, one chapter mentioned the possibility to run with CPU. However it is for the next step: prediction.
I wonder if it is possible to deal with this step as well? As I'm working with a TF which is not well defined, so that cannot skip this step.

Looking forward to your suggestions! Thank you.

Best,
Menghan

**Comment by adamyhe** [comment]
The `fit` class function in bpnet is hard-coded to use cuda, so you'll have to modify the source code to get it to run on non-Nvidia hardware. Not sure why it's not running on your server, sounds like a cuda issue?

**Comment by jamesgalante** [comment]
I was able to use Mac M1 GPUs with the following:

```
# Set the device
device = "mps" if torch.backends.mps.is_available() else "cpu"

# Initialize the BPNet model with MPS, formatted for TF binding prediction
model = BPNet(
    n_outputs=2,
    n_control_tracks=2,
    trimming=(2114 - 1000) // 2
).to(device)
```

with everything else the same - GPU utilization gets up to around 90% for me.

**Comment by adamyhe** [comment]
The 0.9.0 update allows both the `fit` method and the CLIs to take in a device parameter, so good to see it works correctly now.
